### ISSUE TITLE
Doris connector to sink data from spark to starrock

### ISSUE THREAD

**Issue by RonnelOvalles** [StarRocks/starrocks-connector-for-apache-spark#23]
Im using Doris connector to sink data from spark to starrocks but it is showing an error on an endpoint

By the way, source using doris connector works perfectly.

Here is an image of the issue:

![image](https://github.com/StarRocks/starrocks-connector-for-apache-spark/assets/120475177/3a220eda-779a-4f4c-ac8d-3b65205dffe4)

**Comment by banmoy** [comment]
we have supported to write data to starrock. Please see https://docs.starrocks.io/en-us/latest/loading/Spark-connector-starrocks
