### ISSUE TITLE
can not find maven module starrocks-stream-load-sdk

### ISSUE THREAD

**Issue by yangzhiyue** [StarRocks/starrocks-connector-for-apache-spark#26]
<dependency>
      <groupId>com.starrocks</groupId>
      <artifactId>starrocks-stream-load-sdk</artifactId>
      <version>1.0-SNAPSHOT</version>
  </dependency>

I am compiling this project at main branch, but it uses a maven module of starrocks-stream-load-sdk, I can not find it. Could you please give its jar or source code.

**Comment by alberttwong** [comment]
```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  7.761 s
[INFO] Finished at: 2023-06-15T07:39:44-07:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project starrocks-spark3_2.12: Could not resolve dependencies for project com.starrocks:starrocks-spark3_2.12:jar:1.0.0: The following artifacts could not be resolved: com.starrocks:starrocks-stream-load-sdk:jar:1.0-SNAPSHOT (absent): Could not find artifact com.starrocks:starrocks-stream-load-sdk:jar:1.0-SNAPSHOT in central (https://repo.maven.apache.org/maven2) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
```

**Comment by alberttwong** [comment]
it's in the starrocks-connector-for-apache-flink project.   There is a subdirectory called starrocks-stream-load-sdk and then run `mvn install` to generate the jar.

**Comment by alberttwong** [comment]
for temp, you can download it here.  https://drive.google.com/file/d/1dLUkGNElB7HldneE-Q6-DLWSouULJxcd/view?usp=sharing

**Comment by alberttwong** [comment]
I put the jar in my local maven cache at /Users/atwong/.m2/repository/com/starrocks/starrocks-stream-load-sdk/1.0-SNAPSHOT

**Comment by banmoy** [comment]
@yangzhiyue the sdk was deployed to the public repository, and you can pull the newest code and retry

**Comment by yangzhiyue** [comment]
thanks for your reply
