### ISSUE TITLE
Download starrocks-spark3_2.12-1.0.0.jar 

### ISSUE THREAD

**Issue by alberttwong** [StarRocks/starrocks-connector-for-apache-spark#29]
[starrocks-spark3_2.12-1.0.0.tgz](https://github.com/StarRocks/starrocks-connector-for-apache-spark/files/11761194/starrocks-spark3_2.12-1.0.0.tgz)

**Comment by banmoy** [comment]
Jars for load array data
spark 3.2
[starrocks-spark-connector-3.2_2.12-1.1.1-SNAPSHOT.jar.tgz](https://github.com/StarRocks/starrocks-connector-for-apache-spark/files/12158837/starrocks-spark-connector-3.2_2.12-1.1.1-SNAPSHOT.jar.tgz)

spark 3.3
[starrocks-spark-connector-3.3_2.12-1.1.1-SNAPSHOT.jar.tgz](https://github.com/StarRocks/starrocks-connector-for-apache-spark/files/12158847/starrocks-spark-connector-3.3_2.12-1.1.1-SNAPSHOT.jar.tgz)

**Comment by banmoy** [comment]
support to load array data natively
[starrocks-spark-connector-3.3_2.12-1.1.1-SNAPSHOT.jar.tgz](https://github.com/StarRocks/starrocks-connector-for-apache-spark/files/12189470/starrocks-spark-connector-3.3_2.12-1.1.1-SNAPSHOT.jar.tgz)
