### ISSUE TITLE
Download starrocks-stream-load-sdk-1.0-SNAPSHOT.jar

### ISSUE THREAD

**Issue by alberttwong** [StarRocks/starrocks-connector-for-apache-spark#30]
[starrocks-stream-load-sdk-1.0-SNAPSHOT.tgz](https://github.com/StarRocks/starrocks-connector-for-apache-spark/files/11761239/starrocks-stream-load-sdk-1.0-SNAPSHOT.tgz)

**Comment by banmoy** [comment]
Now you can download here https://s01.oss.sonatype.org/content/repositories/snapshots/com/starrocks/starrocks-stream-load-sdk/
