### ISSUE TITLE
依赖tomcat jar 冲突

### ISSUE THREAD

**Issue by melin** [StarRocks/starrocks-connector-for-apache-spark#65]
项目使用spring boot，starrocks 依赖的tomcat 与spring boot 发生冲突，不是理解 starrocks-spark-connector为什么会依赖tomcat，能否去掉，目前starrocks-spark-connector  jar 也比较大，建议精简一些。
![image](https://github.com/StarRocks/starrocks-connector-for-apache-spark/assets/1145830/da720dca-a585-4461-b943-9fc9735905fd)

**Comment by banmoy** [comment]
We have simplified the jar in the newest cod of main brach
