### ISSUE TITLE
Where can I download starrocks-stream-load-sdk ?

### ISSUE THREAD

**Issue by JinyLeeChina** [StarRocks/starrocks-connector-for-apache-spark#7]
Where can I download starrocks-stream-load-sdk ?

**Comment by JinyLeeChina** [comment]
![image](https://user-images.githubusercontent.com/42576980/192720756-2929cc74-7bbc-4e25-b8d9-75f07e118e1b.png)

**Comment by hongli-my** [comment]
here : https://github.com/StarRocks/starrocks-connector-for-apache-flink/tree/main/starrocks-stream-load-sdk
